services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - open-webui-data:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3010}:8080
    env_file:
      - .env
    networks:
      - open-webui
      - apinetwork

volumes:
  open-webui-data:

networks:
  open-webui:
    name: open-webui
  apinetwork:
    name: apinetwork
